### ISSUE TITLE
TypeError: ArrayField.empty_field при попытке сгенерировать транскрипции

### ISSUE THREAD

**Issue by SN4KEBYTE** [DinoTheDinosaur/russian_g2p_neuro#1]
Привет!
При попытке сгенерировать транскрипции получаю следующую ошибку:

(venv) root@2ec29cc40d45:/opt# generate_transcriptions asr/test.txt asr/output.dict
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/venv/lib/python3.8/site-packages/russian_g2p_neuro-1.0.0-py3.8.egg/src/generate_transcriptions.py", line 6, in <module>
    from src.model import Russian_G2P
  File "/opt/venv/lib/python3.8/site-packages/russian_g2p_neuro-1.0.0-py3.8.egg/src/model.py", line 4, in <module>
    from allennlp.data.dataset_readers.seq2seq import Seq2SeqDatasetReader
  File "/opt/venv/lib/python3.8/site-packages/allennlp-0.9.0-py3.8.egg/allennlp/data/__init__.py", line 1, in <module>
    from allennlp.data.dataset_readers.dataset_reader import DatasetReader
  File "/opt/venv/lib/python3.8/site-packages/allennlp-0.9.0-py3.8.egg/allennlp/data/dataset_readers/__init__.py", line 10, in <module>
    from allennlp.data.dataset_readers.ccgbank import CcgBankDatasetReader
  File "/opt/venv/lib/python3.8/site-packages/allennlp-0.9.0-py3.8.egg/allennlp/data/dataset_readers/ccgbank.py", line 9, in <module>
    from allennlp.data.dataset_readers.dataset_reader import DatasetReader
  File "/opt/venv/lib/python3.8/site-packages/allennlp-0.9.0-py3.8.egg/allennlp/data/dataset_readers/dataset_reader.py", line 8, in <module>
    from allennlp.data.instance import Instance
  File "/opt/venv/lib/python3.8/site-packages/allennlp-0.9.0-py3.8.egg/allennlp/data/instance.py", line 3, in <module>
    from allennlp.data.fields.field import DataArray, Field
  File "/opt/venv/lib/python3.8/site-packages/allennlp-0.9.0-py3.8.egg/allennlp/data/fields/__init__.py", line 7, in <module>
    from allennlp.data.fields.array_field import ArrayField
  File "/opt/venv/lib/python3.8/site-packages/allennlp-0.9.0-py3.8.egg/allennlp/data/fields/array_field.py", line 10, in <module>
    class ArrayField(Field[numpy.ndarray]):
  File "/opt/venv/lib/python3.8/site-packages/allennlp-0.9.0-py3.8.egg/allennlp/data/fields/array_field.py", line 51, in ArrayField
    def empty_field(self):  # pylint: disable=no-self-use
  File "/opt/venv/lib/python3.8/site-packages/overrides-6.1.0-py3.8.egg/overrides/overrides.py", line 88, in overrides
    return _overrides(method, check_signature, check_at_runtime)
  File "/opt/venv/lib/python3.8/site-packages/overrides-6.1.0-py3.8.egg/overrides/overrides.py", line 114, in _overrides
    _validate_method(method, super_class, check_signature)
  File "/opt/venv/lib/python3.8/site-packages/overrides-6.1.0-py3.8.egg/overrides/overrides.py", line 135, in _validate_method
    ensure_signature_is_compatible(super_method, method, is_static)
  File "/opt/venv/lib/python3.8/site-packages/overrides-6.1.0-py3.8.egg/overrides/signature.py", line 93, in ensure_signature_is_compatible
    ensure_return_type_compatibility(super_type_hints, sub_type_hints, method_name)
  File "/opt/venv/lib/python3.8/site-packages/overrides-6.1.0-py3.8.egg/overrides/signature.py", line 287, in ensure_return_type_compatibility
    raise TypeError(
TypeError: ArrayField.empty_field: return type `None` is not a `<class 'allennlp.data.fields.field.Field'>`.

Python 3.8.6, пробовал оба способа установки из README. В чем может быть проблема?

**Comment by SN4KEBYTE** [comment]
Проблему решил, создал PR:
https://github.com/DinoTheDinosaur/russian_g2p_neuro/pull/2
